/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CallRouteImport } from './routes/call'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TechRouteImport } from './routes/tech'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as AdminAgentRouteImport } from './routes/admin.agent'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWarrantyRouteImport } from './routes/admin.warranty'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreProductIdRouteImport } from './routes/store.$productId'
import { Route as TechIndexRouteImport } from './routes/tech.index'
import { Route as TechHistoryRouteImport } from './routes/tech.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRoute = TechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentRoute = AdminAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWarrantyRoute = AdminWarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => AdminRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreProductIdRoute = StoreProductIdRouteImport.update({
  id: '/store/$productId',
  path: '/store/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const TechIndexRoute = TechIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechRoute,
} as any)
const TechHistoryRoute = TechHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => TechRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/call': typeof CallRoute
  '/cart': typeof CartRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/tech': typeof TechRouteWithChildren
  '/warranty': typeof WarrantyRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warranty': typeof AdminWarrantyRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/store/$productId': typeof StoreProductIdRoute
  '/tech/history': typeof TechHistoryRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/store/': typeof StoreIndexRoute
  '/tech/': typeof TechIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/cart': typeof CartRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/warranty': typeof WarrantyRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warranty': typeof AdminWarrantyRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/store/$productId': typeof StoreProductIdRoute
  '/tech/history': typeof TechHistoryRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/store': typeof StoreIndexRoute
  '/tech': typeof TechIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/call': typeof CallRoute
  '/cart': typeof CartRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/tech': typeof TechRouteWithChildren
  '/warranty': typeof WarrantyRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warranty': typeof AdminWarrantyRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/store/$productId': typeof StoreProductIdRoute
  '/tech/history': typeof TechHistoryRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/store/': typeof StoreIndexRoute
  '/tech/': typeof TechIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/call'
    | '/cart'
    | '/profile'
    | '/services'
    | '/tech'
    | '/warranty'
    | '/admin/accounts'
    | '/admin/agent'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/warranty'
    | '/orders/$orderId'
    | '/store/$productId'
    | '/tech/history'
    | '/admin/'
    | '/orders/'
    | '/store/'
    | '/tech/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call'
    | '/cart'
    | '/profile'
    | '/services'
    | '/warranty'
    | '/admin/accounts'
    | '/admin/agent'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/warranty'
    | '/orders/$orderId'
    | '/store/$productId'
    | '/tech/history'
    | '/admin'
    | '/orders'
    | '/store'
    | '/tech'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/call'
    | '/cart'
    | '/profile'
    | '/services'
    | '/tech'
    | '/warranty'
    | '/admin/accounts'
    | '/admin/agent'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/warranty'
    | '/orders/$orderId'
    | '/store/$productId'
    | '/tech/history'
    | '/admin/'
    | '/orders/'
    | '/store/'
    | '/tech/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CallRoute: typeof CallRoute
  CartRoute: typeof CartRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  TechRoute: typeof TechRouteWithChildren
  WarrantyRoute: typeof WarrantyRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  StoreProductIdRoute: typeof StoreProductIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech': {
      id: '/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof TechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agent': {
      id: '/admin/agent'
      path: '/agent'
      fullPath: '/admin/agent'
      preLoaderRoute: typeof AdminAgentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/warranty': {
      id: '/admin/warranty'
      path: '/warranty'
      fullPath: '/admin/warranty'
      preLoaderRoute: typeof AdminWarrantyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$productId': {
      id: '/store/$productId'
      path: '/store/$productId'
      fullPath: '/store/$productId'
      preLoaderRoute: typeof StoreProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/': {
      id: '/tech/'
      path: '/'
      fullPath: '/tech/'
      preLoaderRoute: typeof TechIndexRouteImport
      parentRoute: typeof TechRoute
    }
    '/tech/history': {
      id: '/tech/history'
      path: '/history'
      fullPath: '/tech/history'
      preLoaderRoute: typeof TechHistoryRouteImport
      parentRoute: typeof TechRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAgentRoute: typeof AdminAgentRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWarrantyRoute: typeof AdminWarrantyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAgentRoute: AdminAgentRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWarrantyRoute: AdminWarrantyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TechRouteChildren {
  TechHistoryRoute: typeof TechHistoryRoute
  TechIndexRoute: typeof TechIndexRoute
}

const TechRouteChildren: TechRouteChildren = {
  TechHistoryRoute: TechHistoryRoute,
  TechIndexRoute: TechIndexRoute,
}

const TechRouteWithChildren = TechRoute._addFileChildren(TechRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CallRoute: CallRoute,
  CartRoute: CartRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  TechRoute: TechRouteWithChildren,
  WarrantyRoute: WarrantyRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  StoreProductIdRoute: StoreProductIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
